name: 'Install Dependencies'
description: "Set Node.js version and Install node modules"
outputs:
  root_cache_key:
    description: 'Key of root dependencise'
    value: ${{ steps.root_lockfile_hash.outputs.hash }}
  grid_cache_key:
    description: 'Key of dependencise'
    value: ${{ steps.grid_lockfile_hash.outputs.hash }}

runs:
  using: "composite"
  steps:
    - name: Use Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
        registry-url: https://registry.npmjs.org/
    - name: Compute dependency cache key
      id: root_lockfile_hash
      run: echo "::set-output name=hash::${{ hashFiles('package-lock.json') }}"
      shell: bash
    - name: Check dependency cache
      uses: actions/cache@v2
      id: root_cache_dependencies
      with:
        path: ${{ env.ROOT_DEPENDENCY_PATHS }}/
        key: ${{ steps.root_lockfile_hash.outputs.hash }}
    - name: Install dependencies
      run: |
        if echo ${{ steps.root_cache_dependencies.outputs.cache-hit }} | grep -c "true"
        then
          echo "Cache hit - skipping dependency installation"
        else
          npm install
        fi
      shell: bash
    - name: Compute dependency cache key (toast.ui-grid)
      working-directory: ${{ env.WORKING_DIRECTORY }}
      id: grid_lockfile_hash
      run: echo "::set-output name=hash::${{ hashFiles('package-lock.json') }}"
      shell: bash
    - name: Check dependency cache (toast.ui-grid)
      uses: actions/cache@v2
      id: grid_cache_dependencies
      with:
        path: ${{ env.CACHED_DEPENDENCY_PATHS }}/
        key: ${{ steps.grid_lockfile_hash.outputs.hash }}
    - name: Install dependencies (toast.ui-grid)
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        if echo ${{ steps.grid_cache_dependencies.outputs.cache-hit }} | grep -c "true"
        then
          echo "Cache hit - skipping dependency installation"
        else
          npm install
        fi
      shell: bash