name: Publish documents
on: [workflow_dispatch]

env:
  WORKING_DIRECTORY: ./packages/toast-ui.grid
  VUE_WRAPPER_DIRECTORY: ./packages/toast-ui.vue-grid
  REACT_WRAPPER_DIRECTORY: ./packages/toast-ui.react-grid
  CACHED_DEPENDENCY_PATHS: ./packages/toast-ui.grid/node_modules
  ROOT_DEPENDENCY_PATHS: ./node_modules
  CACHED_BUILD_PATHS: ./packages/toast-ui.grid/dist
  BUILD_CACHE_KEY: ${{ github.sha }}

jobs:
  install_dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: install_dependencies
        id: cache-keys
        uses: ./.github/actions/install-dependencies
        with:
          ROOT_DEPENDENCY_PATHS: ${{ env.ROOT_DEPENDENCY_PATHS }}
          CACHED_DEPENDENCY_PATHS: ${{ env.CACHED_DEPENDENCY_PATHS }}
          WORKING_DIRECTORY: ${{ env.WORKING_DIRECTORY }}
    outputs:
      root_cache_key: ${{ steps.cache-keys.outputs.root_cache_key }}
      grid_cache_key: ${{ steps.cache-keys.outputs.grid_cache_key }}

  publish-docs:
    needs: [install_dependencies]
    name: Publish documents
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Publish documents
        uses: ./.github/actions/publish-docs
        with:
          ROOT_DEPENDENCY_PATHS: ${{ env.ROOT_DEPENDENCY_PATHS }}
          CACHED_DEPENDENCY_PATHS: ${{ env.CACHED_DEPENDENCY_PATHS }}
          WORKING_DIRECTORY: ${{ env.WORKING_DIRECTORY }}
          ROOT_CACHE_KEY: ${{ needs.install_dependencies.outputs.root_cache_key }}
          GRID_CACHE_KEY: ${{ needs.install_dependencies.outputs.grid_cache_key }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}