name: Publish wrapper
on: [workflow_dispatch]

env:
  WORKING_DIRECTORY: ./packages/toast-ui.grid
  VUE_WRAPPER_DIRECTORY: ./packages/toast-ui.vue-grid
  REACT_WRAPPER_DIRECTORY: ./packages/toast-ui.react-grid

jobs:
  publish-wrapper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
          registry-url: https://registry.npmjs.org/
      - name: Get package version
        id: version
        uses: PostHog/check-package-version@v2
        with:
          path: ${{ env.WORKING_DIRECTORY }}/
      - name: Update package.json of wrappers
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm run update:wrapper
      - name: Vue wrapper lock update
        working-directory: ${{ env.VUE_WRAPPER_DIRECTORY }}
        run: |
          npm install
      - name: Build vue wrapper
        working-directory: ${{ env.VUE_WRAPPER_DIRECTORY }}
        run: |
          npm run build
      - name: React wrapper lock update
        working-directory: ${{ env.REACT_WRAPPER_DIRECTORY }}
        run: |
          npm install
      - name: Build react wrapper
        working-directory: ${{ env.REACT_WRAPPER_DIRECTORY }}
        run: |
          npm run build
      - name: Commit files
        run: |
          git config --local user.email "daeyeon.kim@nhn.com"
          git config --local user.name "jajugoguma"
          git add .
          git commit -m "chore: update version of wrappers to v${{ steps.version.outputs.committed-version }}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
      - name: Publish vue wrapper
        working-directory: ${{ env.VUE_WRAPPER_DIRECTORY }}
        run: |
          npm publish
      - name: Publish react wrapper
        working-directory: ${{ env.REACT_WRAPPER_DIRECTORY }}
        run: |
          npm publish